// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: ai_scheduler.proto

package cultivation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AISchedulerService_ScheduleDecision_FullMethodName    = "/cultivation.AISchedulerService/ScheduleDecision"
	AISchedulerService_ExecuteBehaviorTree_FullMethodName = "/cultivation.AISchedulerService/ExecuteBehaviorTree"
	AISchedulerService_RegisterNPC_FullMethodName         = "/cultivation.AISchedulerService/RegisterNPC"
	AISchedulerService_UnregisterNPC_FullMethodName       = "/cultivation.AISchedulerService/UnregisterNPC"
)

// AISchedulerServiceClient is the client API for AISchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AISchedulerServiceClient interface {
	ScheduleDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
	ExecuteBehaviorTree(ctx context.Context, in *BehaviorTreeRequest, opts ...grpc.CallOption) (*BehaviorTreeResponse, error)
	RegisterNPC(ctx context.Context, in *NPCRegisterRequest, opts ...grpc.CallOption) (*NPCRegisterResponse, error)
	UnregisterNPC(ctx context.Context, in *NPCUnregisterRequest, opts ...grpc.CallOption) (*NPCUnregisterResponse, error)
}

type aISchedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAISchedulerServiceClient(cc grpc.ClientConnInterface) AISchedulerServiceClient {
	return &aISchedulerServiceClient{cc}
}

func (c *aISchedulerServiceClient) ScheduleDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, AISchedulerService_ScheduleDecision_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aISchedulerServiceClient) ExecuteBehaviorTree(ctx context.Context, in *BehaviorTreeRequest, opts ...grpc.CallOption) (*BehaviorTreeResponse, error) {
	out := new(BehaviorTreeResponse)
	err := c.cc.Invoke(ctx, AISchedulerService_ExecuteBehaviorTree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aISchedulerServiceClient) RegisterNPC(ctx context.Context, in *NPCRegisterRequest, opts ...grpc.CallOption) (*NPCRegisterResponse, error) {
	out := new(NPCRegisterResponse)
	err := c.cc.Invoke(ctx, AISchedulerService_RegisterNPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aISchedulerServiceClient) UnregisterNPC(ctx context.Context, in *NPCUnregisterRequest, opts ...grpc.CallOption) (*NPCUnregisterResponse, error) {
	out := new(NPCUnregisterResponse)
	err := c.cc.Invoke(ctx, AISchedulerService_UnregisterNPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AISchedulerServiceServer is the server API for AISchedulerService service.
// All implementations must embed UnimplementedAISchedulerServiceServer
// for forward compatibility
type AISchedulerServiceServer interface {
	ScheduleDecision(context.Context, *DecisionRequest) (*DecisionResponse, error)
	ExecuteBehaviorTree(context.Context, *BehaviorTreeRequest) (*BehaviorTreeResponse, error)
	RegisterNPC(context.Context, *NPCRegisterRequest) (*NPCRegisterResponse, error)
	UnregisterNPC(context.Context, *NPCUnregisterRequest) (*NPCUnregisterResponse, error)
	mustEmbedUnimplementedAISchedulerServiceServer()
}

// UnimplementedAISchedulerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAISchedulerServiceServer struct {
}

func (UnimplementedAISchedulerServiceServer) ScheduleDecision(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleDecision not implemented")
}
func (UnimplementedAISchedulerServiceServer) ExecuteBehaviorTree(context.Context, *BehaviorTreeRequest) (*BehaviorTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteBehaviorTree not implemented")
}
func (UnimplementedAISchedulerServiceServer) RegisterNPC(context.Context, *NPCRegisterRequest) (*NPCRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNPC not implemented")
}
func (UnimplementedAISchedulerServiceServer) UnregisterNPC(context.Context, *NPCUnregisterRequest) (*NPCUnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterNPC not implemented")
}
func (UnimplementedAISchedulerServiceServer) mustEmbedUnimplementedAISchedulerServiceServer() {}

// UnsafeAISchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AISchedulerServiceServer will
// result in compilation errors.
type UnsafeAISchedulerServiceServer interface {
	mustEmbedUnimplementedAISchedulerServiceServer()
}

func RegisterAISchedulerServiceServer(s grpc.ServiceRegistrar, srv AISchedulerServiceServer) {
	s.RegisterService(&AISchedulerService_ServiceDesc, srv)
}

func _AISchedulerService_ScheduleDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISchedulerServiceServer).ScheduleDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISchedulerService_ScheduleDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISchedulerServiceServer).ScheduleDecision(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AISchedulerService_ExecuteBehaviorTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BehaviorTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISchedulerServiceServer).ExecuteBehaviorTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISchedulerService_ExecuteBehaviorTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISchedulerServiceServer).ExecuteBehaviorTree(ctx, req.(*BehaviorTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AISchedulerService_RegisterNPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NPCRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISchedulerServiceServer).RegisterNPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISchedulerService_RegisterNPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISchedulerServiceServer).RegisterNPC(ctx, req.(*NPCRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AISchedulerService_UnregisterNPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NPCUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AISchedulerServiceServer).UnregisterNPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AISchedulerService_UnregisterNPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AISchedulerServiceServer).UnregisterNPC(ctx, req.(*NPCUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AISchedulerService_ServiceDesc is the grpc.ServiceDesc for AISchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AISchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cultivation.AISchedulerService",
	HandlerType: (*AISchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleDecision",
			Handler:    _AISchedulerService_ScheduleDecision_Handler,
		},
		{
			MethodName: "ExecuteBehaviorTree",
			Handler:    _AISchedulerService_ExecuteBehaviorTree_Handler,
		},
		{
			MethodName: "RegisterNPC",
			Handler:    _AISchedulerService_RegisterNPC_Handler,
		},
		{
			MethodName: "UnregisterNPC",
			Handler:    _AISchedulerService_UnregisterNPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_scheduler.proto",
}
