// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: entity.proto

package cultivation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Realm         string                 `protobuf:"bytes,4,opt,name=realm,proto3" json:"realm,omitempty"`
	Position      *WorldPosition         `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Attributes    *Attributes            `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Karma         *Karma                 `protobuf:"bytes,7,opt,name=karma,proto3" json:"karma,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SpiritStones  *SpiritStones          `protobuf:"bytes,11,opt,name=spirit_stones,json=spiritStones,proto3" json:"spirit_stones,omitempty"`
	Spells        []*SpellData           `protobuf:"bytes,12,rep,name=spells,proto3" json:"spells,omitempty"`
	Items         []*ItemData            `protobuf:"bytes,13,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Entity) GetPosition() *WorldPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Entity) GetAttributes() *Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetKarma() *Karma {
	if x != nil {
		return x.Karma
	}
	return nil
}

func (x *Entity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Entity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Entity) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Entity) GetSpiritStones() *SpiritStones {
	if x != nil {
		return x.SpiritStones
	}
	return nil
}

func (x *Entity) GetSpells() []*SpellData {
	if x != nil {
		return x.Spells
	}
	return nil
}

func (x *Entity) GetItems() []*ItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

type WorldPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldPosition) Reset() {
	*x = WorldPosition{}
	mi := &file_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldPosition) ProtoMessage() {}

func (x *WorldPosition) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldPosition.ProtoReflect.Descriptor instead.
func (*WorldPosition) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{1}
}

func (x *WorldPosition) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *WorldPosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldPosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Attributes struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Qi                  float64                `protobuf:"fixed64,1,opt,name=qi,proto3" json:"qi,omitempty"`
	MaxQi               float64                `protobuf:"fixed64,2,opt,name=max_qi,json=maxQi,proto3" json:"max_qi,omitempty"`
	SpiritualPower      float64                `protobuf:"fixed64,3,opt,name=spiritual_power,json=spiritualPower,proto3" json:"spiritual_power,omitempty"`
	MaxSpiritualPower   float64                `protobuf:"fixed64,4,opt,name=max_spiritual_power,json=maxSpiritualPower,proto3" json:"max_spiritual_power,omitempty"`
	DivineSense         float64                `protobuf:"fixed64,5,opt,name=divine_sense,json=divineSense,proto3" json:"divine_sense,omitempty"`
	Comprehension       int32                  `protobuf:"varint,6,opt,name=comprehension,proto3" json:"comprehension,omitempty"`
	Constitution        int32                  `protobuf:"varint,7,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Luck                int32                  `protobuf:"varint,8,opt,name=luck,proto3" json:"luck,omitempty"`
	CultivationProgress float64                `protobuf:"fixed64,9,opt,name=cultivation_progress,json=cultivationProgress,proto3" json:"cultivation_progress,omitempty"`
	AttackPower         float64                `protobuf:"fixed64,10,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Defense             float64                `protobuf:"fixed64,11,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed               float64                `protobuf:"fixed64,12,opt,name=speed,proto3" json:"speed,omitempty"`
	MentalStability     int32                  `protobuf:"varint,13,opt,name=mental_stability,json=mentalStability,proto3" json:"mental_stability,omitempty"`
	RemainingLifespan   int32                  `protobuf:"varint,14,opt,name=remaining_lifespan,json=remainingLifespan,proto3" json:"remaining_lifespan,omitempty"`
	MaxLifespan         int32                  `protobuf:"varint,15,opt,name=max_lifespan,json=maxLifespan,proto3" json:"max_lifespan,omitempty"`
	// Combat attributes
	CritRate        float64 `protobuf:"fixed64,16,opt,name=crit_rate,json=critRate,proto3" json:"crit_rate,omitempty"`
	CritDamage      float64 `protobuf:"fixed64,17,opt,name=crit_damage,json=critDamage,proto3" json:"crit_damage,omitempty"`
	DodgeRate       float64 `protobuf:"fixed64,18,opt,name=dodge_rate,json=dodgeRate,proto3" json:"dodge_rate,omitempty"`
	HitRate         float64 `protobuf:"fixed64,19,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	Penetration     float64 `protobuf:"fixed64,20,opt,name=penetration,proto3" json:"penetration,omitempty"`
	DamageReduction float64 `protobuf:"fixed64,21,opt,name=damage_reduction,json=damageReduction,proto3" json:"damage_reduction,omitempty"`
	// Life skills
	AlchemyLevel    int32 `protobuf:"varint,22,opt,name=alchemy_level,json=alchemyLevel,proto3" json:"alchemy_level,omitempty"`
	ArtificingLevel int32 `protobuf:"varint,23,opt,name=artificing_level,json=artificingLevel,proto3" json:"artificing_level,omitempty"`
	FormationLevel  int32 `protobuf:"varint,24,opt,name=formation_level,json=formationLevel,proto3" json:"formation_level,omitempty"`
	FireControl     int32 `protobuf:"varint,25,opt,name=fire_control,json=fireControl,proto3" json:"fire_control,omitempty"`
	HerbKnowledge   int32 `protobuf:"varint,26,opt,name=herb_knowledge,json=herbKnowledge,proto3" json:"herb_knowledge,omitempty"`
	MiningSkill     int32 `protobuf:"varint,27,opt,name=mining_skill,json=miningSkill,proto3" json:"mining_skill,omitempty"`
	TalismanSkill   int32 `protobuf:"varint,28,opt,name=talisman_skill,json=talismanSkill,proto3" json:"talisman_skill,omitempty"`
	BeastTaming     int32 `protobuf:"varint,29,opt,name=beast_taming,json=beastTaming,proto3" json:"beast_taming,omitempty"`
	// Social
	Reputation       int32 `protobuf:"varint,30,opt,name=reputation,proto3" json:"reputation,omitempty"`
	SectContribution int32 `protobuf:"varint,31,opt,name=sect_contribution,json=sectContribution,proto3" json:"sect_contribution,omitempty"`
	// Mental / Spiritual
	DaoHeart      int32 `protobuf:"varint,32,opt,name=dao_heart,json=daoHeart,proto3" json:"dao_heart,omitempty"`
	Enlightenment int32 `protobuf:"varint,33,opt,name=enlightenment,proto3" json:"enlightenment,omitempty"`
	RootPurity    int32 `protobuf:"varint,34,opt,name=root_purity,json=rootPurity,proto3" json:"root_purity,omitempty"`
	PoisonLevel   int32 `protobuf:"varint,35,opt,name=poison_level,json=poisonLevel,proto3" json:"poison_level,omitempty"`
	CurseLevel    int32 `protobuf:"varint,36,opt,name=curse_level,json=curseLevel,proto3" json:"curse_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attributes) Reset() {
	*x = Attributes{}
	mi := &file_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attributes) ProtoMessage() {}

func (x *Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attributes.ProtoReflect.Descriptor instead.
func (*Attributes) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{2}
}

func (x *Attributes) GetQi() float64 {
	if x != nil {
		return x.Qi
	}
	return 0
}

func (x *Attributes) GetMaxQi() float64 {
	if x != nil {
		return x.MaxQi
	}
	return 0
}

func (x *Attributes) GetSpiritualPower() float64 {
	if x != nil {
		return x.SpiritualPower
	}
	return 0
}

func (x *Attributes) GetMaxSpiritualPower() float64 {
	if x != nil {
		return x.MaxSpiritualPower
	}
	return 0
}

func (x *Attributes) GetDivineSense() float64 {
	if x != nil {
		return x.DivineSense
	}
	return 0
}

func (x *Attributes) GetComprehension() int32 {
	if x != nil {
		return x.Comprehension
	}
	return 0
}

func (x *Attributes) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *Attributes) GetLuck() int32 {
	if x != nil {
		return x.Luck
	}
	return 0
}

func (x *Attributes) GetCultivationProgress() float64 {
	if x != nil {
		return x.CultivationProgress
	}
	return 0
}

func (x *Attributes) GetAttackPower() float64 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Attributes) GetDefense() float64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Attributes) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Attributes) GetMentalStability() int32 {
	if x != nil {
		return x.MentalStability
	}
	return 0
}

func (x *Attributes) GetRemainingLifespan() int32 {
	if x != nil {
		return x.RemainingLifespan
	}
	return 0
}

func (x *Attributes) GetMaxLifespan() int32 {
	if x != nil {
		return x.MaxLifespan
	}
	return 0
}

func (x *Attributes) GetCritRate() float64 {
	if x != nil {
		return x.CritRate
	}
	return 0
}

func (x *Attributes) GetCritDamage() float64 {
	if x != nil {
		return x.CritDamage
	}
	return 0
}

func (x *Attributes) GetDodgeRate() float64 {
	if x != nil {
		return x.DodgeRate
	}
	return 0
}

func (x *Attributes) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *Attributes) GetPenetration() float64 {
	if x != nil {
		return x.Penetration
	}
	return 0
}

func (x *Attributes) GetDamageReduction() float64 {
	if x != nil {
		return x.DamageReduction
	}
	return 0
}

func (x *Attributes) GetAlchemyLevel() int32 {
	if x != nil {
		return x.AlchemyLevel
	}
	return 0
}

func (x *Attributes) GetArtificingLevel() int32 {
	if x != nil {
		return x.ArtificingLevel
	}
	return 0
}

func (x *Attributes) GetFormationLevel() int32 {
	if x != nil {
		return x.FormationLevel
	}
	return 0
}

func (x *Attributes) GetFireControl() int32 {
	if x != nil {
		return x.FireControl
	}
	return 0
}

func (x *Attributes) GetHerbKnowledge() int32 {
	if x != nil {
		return x.HerbKnowledge
	}
	return 0
}

func (x *Attributes) GetMiningSkill() int32 {
	if x != nil {
		return x.MiningSkill
	}
	return 0
}

func (x *Attributes) GetTalismanSkill() int32 {
	if x != nil {
		return x.TalismanSkill
	}
	return 0
}

func (x *Attributes) GetBeastTaming() int32 {
	if x != nil {
		return x.BeastTaming
	}
	return 0
}

func (x *Attributes) GetReputation() int32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

func (x *Attributes) GetSectContribution() int32 {
	if x != nil {
		return x.SectContribution
	}
	return 0
}

func (x *Attributes) GetDaoHeart() int32 {
	if x != nil {
		return x.DaoHeart
	}
	return 0
}

func (x *Attributes) GetEnlightenment() int32 {
	if x != nil {
		return x.Enlightenment
	}
	return 0
}

func (x *Attributes) GetRootPurity() int32 {
	if x != nil {
		return x.RootPurity
	}
	return 0
}

func (x *Attributes) GetPoisonLevel() int32 {
	if x != nil {
		return x.PoisonLevel
	}
	return 0
}

func (x *Attributes) GetCurseLevel() int32 {
	if x != nil {
		return x.CurseLevel
	}
	return 0
}

type Karma struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KarmaValue    int32                  `protobuf:"varint,1,opt,name=karma_value,json=karmaValue,proto3" json:"karma_value,omitempty"`
	Merit         int32                  `protobuf:"varint,2,opt,name=merit,proto3" json:"merit,omitempty"`
	HeavenlyMark  string                 `protobuf:"bytes,3,opt,name=heavenly_mark,json=heavenlyMark,proto3" json:"heavenly_mark,omitempty"`
	KarmicDebt    int32                  `protobuf:"varint,4,opt,name=karmic_debt,json=karmicDebt,proto3" json:"karmic_debt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Karma) Reset() {
	*x = Karma{}
	mi := &file_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Karma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Karma) ProtoMessage() {}

func (x *Karma) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Karma.ProtoReflect.Descriptor instead.
func (*Karma) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{3}
}

func (x *Karma) GetKarmaValue() int32 {
	if x != nil {
		return x.KarmaValue
	}
	return 0
}

func (x *Karma) GetMerit() int32 {
	if x != nil {
		return x.Merit
	}
	return 0
}

func (x *Karma) GetHeavenlyMark() string {
	if x != nil {
		return x.HeavenlyMark
	}
	return ""
}

func (x *Karma) GetKarmicDebt() int32 {
	if x != nil {
		return x.KarmicDebt
	}
	return 0
}

type SpiritStones struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowGrade      int64                  `protobuf:"varint,1,opt,name=low_grade,json=lowGrade,proto3" json:"low_grade,omitempty"`
	MediumGrade   int64                  `protobuf:"varint,2,opt,name=medium_grade,json=mediumGrade,proto3" json:"medium_grade,omitempty"`
	HighGrade     int64                  `protobuf:"varint,3,opt,name=high_grade,json=highGrade,proto3" json:"high_grade,omitempty"`
	PremiumGrade  int64                  `protobuf:"varint,4,opt,name=premium_grade,json=premiumGrade,proto3" json:"premium_grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpiritStones) Reset() {
	*x = SpiritStones{}
	mi := &file_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpiritStones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiritStones) ProtoMessage() {}

func (x *SpiritStones) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiritStones.ProtoReflect.Descriptor instead.
func (*SpiritStones) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{4}
}

func (x *SpiritStones) GetLowGrade() int64 {
	if x != nil {
		return x.LowGrade
	}
	return 0
}

func (x *SpiritStones) GetMediumGrade() int64 {
	if x != nil {
		return x.MediumGrade
	}
	return 0
}

func (x *SpiritStones) GetHighGrade() int64 {
	if x != nil {
		return x.HighGrade
	}
	return 0
}

func (x *SpiritStones) GetPremiumGrade() int64 {
	if x != nil {
		return x.PremiumGrade
	}
	return 0
}

type SpellData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpellId           string                 `protobuf:"bytes,1,opt,name=spell_id,json=spellId,proto3" json:"spell_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SpellType         string                 `protobuf:"bytes,3,opt,name=spell_type,json=spellType,proto3" json:"spell_type,omitempty"`
	Element           string                 `protobuf:"bytes,4,opt,name=element,proto3" json:"element,omitempty"`
	Cost              int32                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	BaseDamage        int32                  `protobuf:"varint,6,opt,name=base_damage,json=baseDamage,proto3" json:"base_damage,omitempty"`
	BaseHeal          int32                  `protobuf:"varint,7,opt,name=base_heal,json=baseHeal,proto3" json:"base_heal,omitempty"`
	Cooldown          int32                  `protobuf:"varint,8,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	Description       string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	RealmRequirement  string                 `protobuf:"bytes,10,opt,name=realm_requirement,json=realmRequirement,proto3" json:"realm_requirement,omitempty"`
	Proficiency       int32                  `protobuf:"varint,11,opt,name=proficiency,proto3" json:"proficiency,omitempty"`
	LastCastAt        int64                  `protobuf:"varint,12,opt,name=last_cast_at,json=lastCastAt,proto3" json:"last_cast_at,omitempty"`
	CooldownRemaining int64                  `protobuf:"varint,13,opt,name=cooldown_remaining,json=cooldownRemaining,proto3" json:"cooldown_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpellData) Reset() {
	*x = SpellData{}
	mi := &file_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellData) ProtoMessage() {}

func (x *SpellData) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellData.ProtoReflect.Descriptor instead.
func (*SpellData) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{5}
}

func (x *SpellData) GetSpellId() string {
	if x != nil {
		return x.SpellId
	}
	return ""
}

func (x *SpellData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpellData) GetSpellType() string {
	if x != nil {
		return x.SpellType
	}
	return ""
}

func (x *SpellData) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

func (x *SpellData) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SpellData) GetBaseDamage() int32 {
	if x != nil {
		return x.BaseDamage
	}
	return 0
}

func (x *SpellData) GetBaseHeal() int32 {
	if x != nil {
		return x.BaseHeal
	}
	return 0
}

func (x *SpellData) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

func (x *SpellData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SpellData) GetRealmRequirement() string {
	if x != nil {
		return x.RealmRequirement
	}
	return ""
}

func (x *SpellData) GetProficiency() int32 {
	if x != nil {
		return x.Proficiency
	}
	return 0
}

func (x *SpellData) GetLastCastAt() int64 {
	if x != nil {
		return x.LastCastAt
	}
	return 0
}

func (x *SpellData) GetCooldownRemaining() int64 {
	if x != nil {
		return x.CooldownRemaining
	}
	return 0
}

type ItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   string                 `protobuf:"bytes,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ItemType      string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Rarity        int32                  `protobuf:"varint,5,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Equipped      bool                   `protobuf:"varint,8,opt,name=equipped,proto3" json:"equipped,omitempty"`
	Slot          string                 `protobuf:"bytes,9,opt,name=slot,proto3" json:"slot,omitempty"`
	Durability    int32                  `protobuf:"varint,10,opt,name=durability,proto3" json:"durability,omitempty"`
	Bound         bool                   `protobuf:"varint,11,opt,name=bound,proto3" json:"bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{6}
}

func (x *ItemData) GetInventoryId() string {
	if x != nil {
		return x.InventoryId
	}
	return ""
}

func (x *ItemData) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemData) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ItemData) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *ItemData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemData) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemData) GetEquipped() bool {
	if x != nil {
		return x.Equipped
	}
	return false
}

func (x *ItemData) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *ItemData) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ItemData) GetBound() bool {
	if x != nil {
		return x.Bound
	}
	return false
}

var File_entity_proto protoreflect.FileDescriptor

const file_entity_proto_rawDesc = "" +
	"\n" +
	"\fentity.proto\x12\vcultivation\"\xf1\x03\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05realm\x18\x04 \x01(\tR\x05realm\x126\n" +
	"\bposition\x18\x05 \x01(\v2\x1a.cultivation.WorldPositionR\bposition\x127\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x17.cultivation.AttributesR\n" +
	"attributes\x12(\n" +
	"\x05karma\x18\a \x01(\v2\x12.cultivation.KarmaR\x05karma\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12>\n" +
	"\rspirit_stones\x18\v \x01(\v2\x19.cultivation.SpiritStonesR\fspiritStones\x12.\n" +
	"\x06spells\x18\f \x03(\v2\x16.cultivation.SpellDataR\x06spells\x12+\n" +
	"\x05items\x18\r \x03(\v2\x15.cultivation.ItemDataR\x05items\"H\n" +
	"\rWorldPosition\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\"\xfa\t\n" +
	"\n" +
	"Attributes\x12\x0e\n" +
	"\x02qi\x18\x01 \x01(\x01R\x02qi\x12\x15\n" +
	"\x06max_qi\x18\x02 \x01(\x01R\x05maxQi\x12'\n" +
	"\x0fspiritual_power\x18\x03 \x01(\x01R\x0espiritualPower\x12.\n" +
	"\x13max_spiritual_power\x18\x04 \x01(\x01R\x11maxSpiritualPower\x12!\n" +
	"\fdivine_sense\x18\x05 \x01(\x01R\vdivineSense\x12$\n" +
	"\rcomprehension\x18\x06 \x01(\x05R\rcomprehension\x12\"\n" +
	"\fconstitution\x18\a \x01(\x05R\fconstitution\x12\x12\n" +
	"\x04luck\x18\b \x01(\x05R\x04luck\x121\n" +
	"\x14cultivation_progress\x18\t \x01(\x01R\x13cultivationProgress\x12!\n" +
	"\fattack_power\x18\n" +
	" \x01(\x01R\vattackPower\x12\x18\n" +
	"\adefense\x18\v \x01(\x01R\adefense\x12\x14\n" +
	"\x05speed\x18\f \x01(\x01R\x05speed\x12)\n" +
	"\x10mental_stability\x18\r \x01(\x05R\x0fmentalStability\x12-\n" +
	"\x12remaining_lifespan\x18\x0e \x01(\x05R\x11remainingLifespan\x12!\n" +
	"\fmax_lifespan\x18\x0f \x01(\x05R\vmaxLifespan\x12\x1b\n" +
	"\tcrit_rate\x18\x10 \x01(\x01R\bcritRate\x12\x1f\n" +
	"\vcrit_damage\x18\x11 \x01(\x01R\n" +
	"critDamage\x12\x1d\n" +
	"\n" +
	"dodge_rate\x18\x12 \x01(\x01R\tdodgeRate\x12\x19\n" +
	"\bhit_rate\x18\x13 \x01(\x01R\ahitRate\x12 \n" +
	"\vpenetration\x18\x14 \x01(\x01R\vpenetration\x12)\n" +
	"\x10damage_reduction\x18\x15 \x01(\x01R\x0fdamageReduction\x12#\n" +
	"\ralchemy_level\x18\x16 \x01(\x05R\falchemyLevel\x12)\n" +
	"\x10artificing_level\x18\x17 \x01(\x05R\x0fartificingLevel\x12'\n" +
	"\x0fformation_level\x18\x18 \x01(\x05R\x0eformationLevel\x12!\n" +
	"\ffire_control\x18\x19 \x01(\x05R\vfireControl\x12%\n" +
	"\x0eherb_knowledge\x18\x1a \x01(\x05R\rherbKnowledge\x12!\n" +
	"\fmining_skill\x18\x1b \x01(\x05R\vminingSkill\x12%\n" +
	"\x0etalisman_skill\x18\x1c \x01(\x05R\rtalismanSkill\x12!\n" +
	"\fbeast_taming\x18\x1d \x01(\x05R\vbeastTaming\x12\x1e\n" +
	"\n" +
	"reputation\x18\x1e \x01(\x05R\n" +
	"reputation\x12+\n" +
	"\x11sect_contribution\x18\x1f \x01(\x05R\x10sectContribution\x12\x1b\n" +
	"\tdao_heart\x18  \x01(\x05R\bdaoHeart\x12$\n" +
	"\renlightenment\x18! \x01(\x05R\renlightenment\x12\x1f\n" +
	"\vroot_purity\x18\" \x01(\x05R\n" +
	"rootPurity\x12!\n" +
	"\fpoison_level\x18# \x01(\x05R\vpoisonLevel\x12\x1f\n" +
	"\vcurse_level\x18$ \x01(\x05R\n" +
	"curseLevel\"\x84\x01\n" +
	"\x05Karma\x12\x1f\n" +
	"\vkarma_value\x18\x01 \x01(\x05R\n" +
	"karmaValue\x12\x14\n" +
	"\x05merit\x18\x02 \x01(\x05R\x05merit\x12#\n" +
	"\rheavenly_mark\x18\x03 \x01(\tR\fheavenlyMark\x12\x1f\n" +
	"\vkarmic_debt\x18\x04 \x01(\x05R\n" +
	"karmicDebt\"\x92\x01\n" +
	"\fSpiritStones\x12\x1b\n" +
	"\tlow_grade\x18\x01 \x01(\x03R\blowGrade\x12!\n" +
	"\fmedium_grade\x18\x02 \x01(\x03R\vmediumGrade\x12\x1d\n" +
	"\n" +
	"high_grade\x18\x03 \x01(\x03R\thighGrade\x12#\n" +
	"\rpremium_grade\x18\x04 \x01(\x03R\fpremiumGrade\"\xa3\x03\n" +
	"\tSpellData\x12\x19\n" +
	"\bspell_id\x18\x01 \x01(\tR\aspellId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"spell_type\x18\x03 \x01(\tR\tspellType\x12\x18\n" +
	"\aelement\x18\x04 \x01(\tR\aelement\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x05R\x04cost\x12\x1f\n" +
	"\vbase_damage\x18\x06 \x01(\x05R\n" +
	"baseDamage\x12\x1b\n" +
	"\tbase_heal\x18\a \x01(\x05R\bbaseHeal\x12\x1a\n" +
	"\bcooldown\x18\b \x01(\x05R\bcooldown\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12+\n" +
	"\x11realm_requirement\x18\n" +
	" \x01(\tR\x10realmRequirement\x12 \n" +
	"\vproficiency\x18\v \x01(\x05R\vproficiency\x12 \n" +
	"\flast_cast_at\x18\f \x01(\x03R\n" +
	"lastCastAt\x12-\n" +
	"\x12cooldown_remaining\x18\r \x01(\x03R\x11cooldownRemaining\"\xb3\x02\n" +
	"\bItemData\x12!\n" +
	"\finventory_id\x18\x01 \x01(\tR\vinventoryId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x16\n" +
	"\x06rarity\x18\x05 \x01(\x05R\x06rarity\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x1a\n" +
	"\bequipped\x18\b \x01(\bR\bequipped\x12\x12\n" +
	"\x04slot\x18\t \x01(\tR\x04slot\x12\x1e\n" +
	"\n" +
	"durability\x18\n" +
	" \x01(\x05R\n" +
	"durability\x12\x14\n" +
	"\x05bound\x18\v \x01(\bR\x05boundB7Z5github.com/cultivation-world/shared/proto;cultivationb\x06proto3"

var (
	file_entity_proto_rawDescOnce sync.Once
	file_entity_proto_rawDescData []byte
)

func file_entity_proto_rawDescGZIP() []byte {
	file_entity_proto_rawDescOnce.Do(func() {
		file_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_proto_rawDesc), len(file_entity_proto_rawDesc)))
	})
	return file_entity_proto_rawDescData
}

var file_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_entity_proto_goTypes = []any{
	(*Entity)(nil),        // 0: cultivation.Entity
	(*WorldPosition)(nil), // 1: cultivation.WorldPosition
	(*Attributes)(nil),    // 2: cultivation.Attributes
	(*Karma)(nil),         // 3: cultivation.Karma
	(*SpiritStones)(nil),  // 4: cultivation.SpiritStones
	(*SpellData)(nil),     // 5: cultivation.SpellData
	(*ItemData)(nil),      // 6: cultivation.ItemData
}
var file_entity_proto_depIdxs = []int32{
	1, // 0: cultivation.Entity.position:type_name -> cultivation.WorldPosition
	2, // 1: cultivation.Entity.attributes:type_name -> cultivation.Attributes
	3, // 2: cultivation.Entity.karma:type_name -> cultivation.Karma
	4, // 3: cultivation.Entity.spirit_stones:type_name -> cultivation.SpiritStones
	5, // 4: cultivation.Entity.spells:type_name -> cultivation.SpellData
	6, // 5: cultivation.Entity.items:type_name -> cultivation.ItemData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_entity_proto_init() }
func file_entity_proto_init() {
	if File_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_proto_rawDesc), len(file_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_proto_goTypes,
		DependencyIndexes: file_entity_proto_depIdxs,
		MessageInfos:      file_entity_proto_msgTypes,
	}.Build()
	File_entity_proto = out.File
	file_entity_proto_goTypes = nil
	file_entity_proto_depIdxs = nil
}
