// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: heavenly_dao.proto

package cultivation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HeavenlyDaoService_EvaluateKarma_FullMethodName    = "/cultivation.HeavenlyDaoService/EvaluateKarma"
	HeavenlyDaoService_CheckTribulation_FullMethodName = "/cultivation.HeavenlyDaoService/CheckTribulation"
	HeavenlyDaoService_BalanceCheck_FullMethodName     = "/cultivation.HeavenlyDaoService/BalanceCheck"
	HeavenlyDaoService_ApplyKarmaDecay_FullMethodName  = "/cultivation.HeavenlyDaoService/ApplyKarmaDecay"
)

// HeavenlyDaoServiceClient is the client API for HeavenlyDaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeavenlyDaoServiceClient interface {
	EvaluateKarma(ctx context.Context, in *KarmaRequest, opts ...grpc.CallOption) (*KarmaResponse, error)
	CheckTribulation(ctx context.Context, in *TribulationRequest, opts ...grpc.CallOption) (*TribulationResponse, error)
	BalanceCheck(ctx context.Context, in *BalanceCheckRequest, opts ...grpc.CallOption) (*BalanceCheckResponse, error)
	ApplyKarmaDecay(ctx context.Context, in *DecayRequest, opts ...grpc.CallOption) (*DecayResponse, error)
}

type heavenlyDaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeavenlyDaoServiceClient(cc grpc.ClientConnInterface) HeavenlyDaoServiceClient {
	return &heavenlyDaoServiceClient{cc}
}

func (c *heavenlyDaoServiceClient) EvaluateKarma(ctx context.Context, in *KarmaRequest, opts ...grpc.CallOption) (*KarmaResponse, error) {
	out := new(KarmaResponse)
	err := c.cc.Invoke(ctx, HeavenlyDaoService_EvaluateKarma_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heavenlyDaoServiceClient) CheckTribulation(ctx context.Context, in *TribulationRequest, opts ...grpc.CallOption) (*TribulationResponse, error) {
	out := new(TribulationResponse)
	err := c.cc.Invoke(ctx, HeavenlyDaoService_CheckTribulation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heavenlyDaoServiceClient) BalanceCheck(ctx context.Context, in *BalanceCheckRequest, opts ...grpc.CallOption) (*BalanceCheckResponse, error) {
	out := new(BalanceCheckResponse)
	err := c.cc.Invoke(ctx, HeavenlyDaoService_BalanceCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heavenlyDaoServiceClient) ApplyKarmaDecay(ctx context.Context, in *DecayRequest, opts ...grpc.CallOption) (*DecayResponse, error) {
	out := new(DecayResponse)
	err := c.cc.Invoke(ctx, HeavenlyDaoService_ApplyKarmaDecay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeavenlyDaoServiceServer is the server API for HeavenlyDaoService service.
// All implementations must embed UnimplementedHeavenlyDaoServiceServer
// for forward compatibility
type HeavenlyDaoServiceServer interface {
	EvaluateKarma(context.Context, *KarmaRequest) (*KarmaResponse, error)
	CheckTribulation(context.Context, *TribulationRequest) (*TribulationResponse, error)
	BalanceCheck(context.Context, *BalanceCheckRequest) (*BalanceCheckResponse, error)
	ApplyKarmaDecay(context.Context, *DecayRequest) (*DecayResponse, error)
	mustEmbedUnimplementedHeavenlyDaoServiceServer()
}

// UnimplementedHeavenlyDaoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHeavenlyDaoServiceServer struct {
}

func (UnimplementedHeavenlyDaoServiceServer) EvaluateKarma(context.Context, *KarmaRequest) (*KarmaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateKarma not implemented")
}
func (UnimplementedHeavenlyDaoServiceServer) CheckTribulation(context.Context, *TribulationRequest) (*TribulationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTribulation not implemented")
}
func (UnimplementedHeavenlyDaoServiceServer) BalanceCheck(context.Context, *BalanceCheckRequest) (*BalanceCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BalanceCheck not implemented")
}
func (UnimplementedHeavenlyDaoServiceServer) ApplyKarmaDecay(context.Context, *DecayRequest) (*DecayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyKarmaDecay not implemented")
}
func (UnimplementedHeavenlyDaoServiceServer) mustEmbedUnimplementedHeavenlyDaoServiceServer() {}

// UnsafeHeavenlyDaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeavenlyDaoServiceServer will
// result in compilation errors.
type UnsafeHeavenlyDaoServiceServer interface {
	mustEmbedUnimplementedHeavenlyDaoServiceServer()
}

func RegisterHeavenlyDaoServiceServer(s grpc.ServiceRegistrar, srv HeavenlyDaoServiceServer) {
	s.RegisterService(&HeavenlyDaoService_ServiceDesc, srv)
}

func _HeavenlyDaoService_EvaluateKarma_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KarmaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeavenlyDaoServiceServer).EvaluateKarma(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeavenlyDaoService_EvaluateKarma_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeavenlyDaoServiceServer).EvaluateKarma(ctx, req.(*KarmaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeavenlyDaoService_CheckTribulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TribulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeavenlyDaoServiceServer).CheckTribulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeavenlyDaoService_CheckTribulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeavenlyDaoServiceServer).CheckTribulation(ctx, req.(*TribulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeavenlyDaoService_BalanceCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeavenlyDaoServiceServer).BalanceCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeavenlyDaoService_BalanceCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeavenlyDaoServiceServer).BalanceCheck(ctx, req.(*BalanceCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeavenlyDaoService_ApplyKarmaDecay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeavenlyDaoServiceServer).ApplyKarmaDecay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeavenlyDaoService_ApplyKarmaDecay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeavenlyDaoServiceServer).ApplyKarmaDecay(ctx, req.(*DecayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeavenlyDaoService_ServiceDesc is the grpc.ServiceDesc for HeavenlyDaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeavenlyDaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cultivation.HeavenlyDaoService",
	HandlerType: (*HeavenlyDaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateKarma",
			Handler:    _HeavenlyDaoService_EvaluateKarma_Handler,
		},
		{
			MethodName: "CheckTribulation",
			Handler:    _HeavenlyDaoService_CheckTribulation_Handler,
		},
		{
			MethodName: "BalanceCheck",
			Handler:    _HeavenlyDaoService_BalanceCheck_Handler,
		},
		{
			MethodName: "ApplyKarmaDecay",
			Handler:    _HeavenlyDaoService_ApplyKarmaDecay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heavenly_dao.proto",
}
