-- Add columns for expanded proto attributes
-- Combat attributes
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS crit_rate DOUBLE PRECISION DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS crit_damage DOUBLE PRECISION DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS dodge_rate DOUBLE PRECISION DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS hit_rate DOUBLE PRECISION DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS penetration DOUBLE PRECISION DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS damage_reduction DOUBLE PRECISION DEFAULT 0;

-- Life skills
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS alchemy_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS artificing_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS mining_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS herb_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS talisman_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS formation_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS fire_control INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS beast_taming INTEGER DEFAULT 0;

-- Social
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS reputation INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS sect_contribution INTEGER DEFAULT 0;

-- Mental / Spiritual
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS dao_heart INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS enlightenment INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS property_value INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS business_income INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS root_purity INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS poison_level INTEGER DEFAULT 0;
ALTER TABLE base_attributes ADD COLUMN IF NOT EXISTS curse_level INTEGER DEFAULT 0;

-- Karma
ALTER TABLE karma_attributes ADD COLUMN IF NOT EXISTS karmic_debt INTEGER DEFAULT 0;
